### ISSUE TITLE
Application is missing the application-identifier entitlement.

### ISSUE THREAD

**Issue by flameaway** [opa334/IGSideloadFix#2]
Hello, no matter how i try to sideload I cannot get this to work. I get a generic error in alt store, but filza gives a little more insight.

![image](https://user-images.githubusercontent.com/8405067/191421719-b752a89c-6321-4b0a-bfee-c7c8c3919aab.png)

**Comment by opa334** [comment]
I don't understand why you would want to install this with a jailbreak. Either install Rocket from your package manager or sign the .app inside the IPA with entitlements.

**Comment by neverabsolute** [comment]
I am also encountering this error. There is very little information online about this. I was trying to install this on a non-jailbroken device, and was trying to debug it on a jailbroken device.
